"""empty message

Revision ID: 28546d6505a1
Revises: cd637d3b4797
Create Date: 2026-02-19 02:49:32.890733

"""
from alembic import op
import sqlalchemy as sa


# revision identifiers, used by Alembic.
revision = '28546d6505a1'
down_revision = 'cd637d3b4797'
branch_labels = None
depends_on = None


def upgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint('comment_author_id_key', type_='unique')
        batch_op.drop_constraint('comment_post_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])
        batch_op.create_foreign_key(None, 'user', ['author_id'], ['id'])

    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint('media_post_id_key', type_='unique')
        batch_op.create_foreign_key(None, 'post', ['post_id'], ['id'])

    # ### end Alembic commands ###


def downgrade():
    # ### commands auto generated by Alembic - please adjust! ###
    with op.batch_alter_table('media', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('media_post_id_key', ['post_id'])

    with op.batch_alter_table('comment', schema=None) as batch_op:
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.drop_constraint(None, type_='foreignkey')
        batch_op.create_unique_constraint('comment_post_id_key', ['post_id'])
        batch_op.create_unique_constraint('comment_author_id_key', ['author_id'])

    # ### end Alembic commands ###
